language: node_js
node_js:
  - '0.10'
before_script:
  - mkdir testdb
  - mongod --port 27017 --dbpath testdb --replSet rs0 --oplogSize 20 --noprealloc --fork --smallfiles --logpath mongodb.log
  - sleep 3
  - mongo admin --eval 'printjson(rs.initiate());'
  - sleep 20
deploy:
  provider: npm
  email: stephensebro@yahoo.com
  api_key:
    secure: GORhsjTrkg5UFhKbnCjPGtDHkbz7LH1x2brO6Q4npfimN9VQB7lzqpaTGYrUZsiODOE1/x7BIwc9tYVeQW4hZpdF2emf79FYw6sC3bMSdTmGwtyfhX8OHIC3MQISZ0EBBStriOURV0llPhyHF9uboI0I8HueoRSuAmgkuu/Hf8c=
  on:
    tags: true
    repo: agco-adm/harvester
    branch: develop
