language: node_js
node_js:
  - '4.2.0'
services:
  - docker
before_script:
  - docker-compose -f docker-compose.test.yml up -d db
  - docker-compose -f docker-compose.test.yml up initReplicaset
  - docker-compose -f docker-compose.test.yml build test
script: docker-compose -f docker-compose.test.yml run test
deploy:
  provider: npm
  email: developer@agcocorp.com
  api_key:
    secure: "ZOFUbJMY9nu1ekRB51bpSMm3DgOsIf3TrqFrW4YflLnLzWIGQTT/K7p+Fjw+uf3GMNojrH8sTT1TyBustt08fobm0iRQq1FhT0xRzz+NsAqGC+DdbbNyUYoKvKGJ3sFvX0XJc65eFu5Zafaf9XidubG9l44INEkNGmpzwY5zy+M="
  on:
    tags: true
    repo: agco/harvesterjs
    branch: master

